# Generated by Django 3.2.23 on 2024-01-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='fname',
            new_name='name',
        ),
    ]
