# Generated by Django 3.2.23 on 2024-02-04 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_record_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='service',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
